project:
  type: website

website:
  title: "Ocean Sustainability"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about_me.ipynb
        text: Me
      - href: intro.ipynb
        text: Intro
      - href: https://github.com/anly501/dsan-5000-project-kendallgilbert180/tree/main/dsan-website/5000-website/codes
        text: Code
      - text: Data
        menu:
        - href: https://github.com/anly501/dsan-5000-project-kendallgilbert180/tree/main/dsan-website/5000-website/data
          text: Data
        - gathering.ipynb
        - cleaning.ipynb
      - text: EDA
        menu:
        - eda/univariate.ipynb
        - eda/multivariate.ipynb
      - text: Naive Bayes
        menu:
        - NB.ipynb
        - FS.ipynb
        - nb_record.ipynb
        - nb_text.ipynb
      - text: Dim Reduction
        menu:
        - dimensionality.ipynb
        - pca.ipynb 
        - t_sne.ipynb
        - comparison.ipynb
      - href: clustering.ipynb
        text: Clustering
      - text: Trees
        menu: 
        - trees.ipynb
        - classification.ipynb
        - regression.ipynb
      - href: conclusions.ipynb
        text: Conclusions
    background: "#B7E0EE"
    foreground: black


format:
  html:
    theme: flatly
    toc: true
    linkcolor: "#9CD7E3"
    #code-fold: true
