project:
  type: website

website:
  title: "Minor League Sports"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about_me.ipynb
        text: Me
      - href: https://github.com/anly501/dsan-5000-project-kendallgilbert180
        text: Code
      - href: intro.ipynb
        text: Introduction
      - href: https://github.com/anly501/dsan-5000-project-kendallgilbert180/tree/main/data
        text: Data
      - text: Data Steps
        menu:
        - gathering.ipynb
        - cleaning.ipynb
        - exploration.ipynb
        - clustering.ipynb
      - href: dimensionality.ipynb
        text: Dimensionality Reduction
      - href: trees.ipynb
        text: Decision Trees
      - href: arm.ipynb
        text: ARM
      - href: conclusions.ipynb
        text: Conclusions

format:
  html:
    theme: flatly 
    toc: true
