project:
  type: website

website:
  title: "Ocean Sustainability"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about_me.ipynb
        text: Me
      - href: https://github.com/anly501/dsan-5000-project-kendallgilbert180
        text: Code
      - href: intro.ipynb
        text: Introduction
      - text: Data
        menu:
        - href: https://github.com/anly501/dsan-5000-project-kendallgilbert180/tree/main/dsan-website/5000-website/data
          text: Data
        - gathering.ipynb
        - cleaning.ipynb
        - exploration.ipynb
        - clustering.ipynb
      - text: ML
        menu:
        - FS.ipynb
        - NB.ipynb
      - href: dimensionality.ipynb
        text: Dimensionality Reduction
      - href: trees.ipynb
        text: Decision Trees
      - href: arm.ipynb
        text: ARM
      - href: conclusions.ipynb
        text: Conclusions

format:
  html:
    theme: simplex 
    background-color: beige;
    toc: true
