project:
  type: website

website:
  title: "Minor League Sports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.ipynb
        text: About Me
      - href: https://github.com/anly501/dsan-5000-project-kendallgilbert180
        text: Code
      - href: intro.ipynb
        text: Introduction
      - href: https://github.com/anly501/dsan-5000-project-kendallgilbert180/tree/main/.github
        text: Data
      - href: gathering.ipynb
        text: Data Gathering
      - href: cleaning.ipynb
        text: Data Cleaning
      - href: exploration.ipynb
        text: Data Exploration
      - href: clustering.ipynb
        text: Data Clustering
      - href: dimensionality.ipynb
        text: Dimensionality Reduction
      - href: trees.ipynb
        text: Decision Trees
      - href: arm.ipynb
        text: ARM
      - href: conclusions.ipynb
        text: Conclusions

format:
  html:
    theme: Darkly
    toc: true
