<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ocean Sustainability - Classification</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Ocean Sustainability</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about_me.html" rel="" target="">
 <span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./intro.html" rel="" target="">
 <span class="menu-text">Intro</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/anly501/dsan-5000-project-kendallgilbert180/tree/main/dsan-website/5000-website/codes" rel="" target="">
 <span class="menu-text">Code</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Data</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-data">    
        <li>
    <a class="dropdown-item" href="https://github.com/anly501/dsan-5000-project-kendallgilbert180/tree/main/dsan-website/5000-website/data" rel="" target="">
 <span class="dropdown-text">Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./gathering.html" rel="" target="">
 <span class="dropdown-text">Data Gathering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cleaning.html" rel="" target="">
 <span class="dropdown-text">Data Cleaning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-eda" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">EDA</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-eda">    
        <li>
    <a class="dropdown-item" href="./eda/univariate.html" rel="" target="">
 <span class="dropdown-text">Data Exploration - Univariate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./eda/multivariate.html" rel="" target="">
 <span class="dropdown-text">Data Exploration - Multivariate</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-naive-bayes" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Naive Bayes</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-naive-bayes">    
        <li>
    <a class="dropdown-item" href="./NB.html" rel="" target="">
 <span class="dropdown-text">Naive Bayes Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./FS.html" rel="" target="">
 <span class="dropdown-text">Feature Selection Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb_record.html" rel="" target="">
 <span class="dropdown-text">Naive Bayes Record Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb_text.html" rel="" target="">
 <span class="dropdown-text">Naive Bayes - Text Data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dim-reduction" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Dim Reduction</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-dim-reduction">    
        <li>
    <a class="dropdown-item" href="./dimensionality.html" rel="" target="">
 <span class="dropdown-text">Dimensionality Reduction Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pca.html" rel="" target="">
 <span class="dropdown-text">PCA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./t_sne.html" rel="" target="">
 <span class="dropdown-text">T-SNE</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./comparison.html" rel="" target="">
 <span class="dropdown-text">PCA vs.&nbsp;T-SNE</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./clustering.html" rel="" target="">
 <span class="menu-text">Clustering</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-trees" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Trees</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-trees">    
        <li>
    <a class="dropdown-item" href="./trees.html" rel="" target="">
 <span class="dropdown-text">Decision Trees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./classification.html" rel="" target="">
 <span class="dropdown-text">Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./regression.html" rel="" target="">
 <span class="dropdown-text">Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./arm.ipynb" rel="" target="">
 <span class="menu-text">ARM</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./conclusions.ipynb" rel="" target="">
 <span class="menu-text">Conclusions</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#decision-tree-classification" id="toc-decision-tree-classification" class="nav-link" data-scroll-target="#decision-tree-classification">Decision Tree Classification</a>
  <ul class="collapse">
  <li><a href="#importing-libraries-and-data" id="toc-importing-libraries-and-data" class="nav-link" data-scroll-target="#importing-libraries-and-data">Importing Libraries and Data</a></li>
  <li><a href="#creating-bins" id="toc-creating-bins" class="nav-link" data-scroll-target="#creating-bins">Creating Bins</a></li>
  <li><a href="#class-distribution" id="toc-class-distribution" class="nav-link" data-scroll-target="#class-distribution">Class Distribution</a></li>
  <li><a href="#baseline-comparison" id="toc-baseline-comparison" class="nav-link" data-scroll-target="#baseline-comparison">Baseline Comparison</a></li>
  <li><a href="#decision-tree-classifier" id="toc-decision-tree-classifier" class="nav-link" data-scroll-target="#decision-tree-classifier">Decision Tree Classifier</a></li>
  <li><a href="#evaluating-performance" id="toc-evaluating-performance" class="nav-link" data-scroll-target="#evaluating-performance">Evaluating Performance</a></li>
  <li><a href="#confusion-matrices" id="toc-confusion-matrices" class="nav-link" data-scroll-target="#confusion-matrices">Confusion Matrices</a></li>
  <li><a href="#plotting-tree" id="toc-plotting-tree" class="nav-link" data-scroll-target="#plotting-tree">Plotting Tree</a></li>
  </ul></li>
  <li><a href="#random-forests" id="toc-random-forests" class="nav-link" data-scroll-target="#random-forests">Random Forests</a>
  <ul class="collapse">
  <li><a href="#random-forest-confusion-matrix" id="toc-random-forest-confusion-matrix" class="nav-link" data-scroll-target="#random-forest-confusion-matrix">Random Forest Confusion Matrix</a></li>
  </ul></li>
  <li><a href="#results-and-conclusions" id="toc-results-and-conclusions" class="nav-link" data-scroll-target="#results-and-conclusions">Results and Conclusions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Classification</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Within this tab I will use a classification decision tree in order to classify certain tuples as sustainable or not.</p>
<p>This model aims to explore whether specific variables are good indicators of the extent to which policies relate to the ocean. The decision tree visualization allows us to see which features are most important in determining the sustainability category. This can provide valuable insights into what action countries are taking and how it has a impact on their sustainability level - which is being classified into the bins.</p>
<p>If the model performs well, the findings could have the ability inform data-driven decision-making in policy development specifically with regard to ocean sustainability and conservation efforts.</p>
<p>By understanding the variables that influence sustainability levels, conservation initiatives can be targeted and tailored to address specific challenges faced by countries.</p>
</section>
<section id="decision-tree-classification" class="level2">
<h2 class="anchored" data-anchor-id="decision-tree-classification">Decision Tree Classification</h2>
<p>The decision tree algorithm works by recursively splitting the data based on the features (attributes) to create a tree-like structure. Each internal node of the tree represents a decision based on a particular feature, and each leaf node represents the class label (1,2,3,4,5). 1 being least sustainable and 5 being most sustainable. The final leaf node reached determines the predicted class for that tuple.</p>
<section id="importing-libraries-and-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-libraries-and-data">Importing Libraries and Data</h3>
<div class="cell" data-execution_count="48">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeClassifier</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, classification_report</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> LabelEncoder</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> plot_tree</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> confusion_matrix, ConfusionMatrixDisplay</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, recall_score, precision_score</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> export_text</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading data</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>trees <span class="op">=</span> pd.read_csv(<span class="st">"/Users/kendallgilbert/dsan-5000-project-kendallgilbert180/dsan-website/5000-website/data/01-modified-data/nb_record.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="creating-bins" class="level3">
<h3 class="anchored" data-anchor-id="creating-bins">Creating Bins</h3>
<p>I created five bins for my target variable.</p>
<p><strong>Target</strong> - Percentage of Policy out of all policy in a year relating to ocean sustainability. I binned these values into five bins. These bins are 0-17, 18-36, 37-54, 55 - 72, 73 - 87. For example, Bin 1 includes countries that have 0-17% of policy relating to ocean sustainability each year, bin 2 is 18-36% of policy relating to sustainability, etc.</p>
<p>The new column Binned_Value was added to use as the target variable.</p>
<div class="cell" data-execution_count="44">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bins for values to be placed in 1, 2, 3, 4, 5</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> trees[<span class="st">'Value'</span>]</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>bin_edges <span class="op">=</span> [<span class="dv">0</span>, <span class="dv">18</span>, <span class="dv">36</span>, <span class="dv">54</span>, <span class="dv">72</span>, <span class="dv">87</span>]</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>y_binned <span class="op">=</span> pd.cut(y, bins<span class="op">=</span>bin_edges, labels<span class="op">=</span><span class="va">False</span>, include_lowest<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>trees[<span class="st">'Binned_Value'</span>] <span class="op">=</span> y_binned <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>trees.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="44">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Aqua Production (Millions)</th>
<th data-quarto-table-cell-role="th">Marine Protected Area (sqkm)</th>
<th data-quarto-table-cell-role="th">Inventions (number)</th>
<th data-quarto-table-cell-role="th">Instruments (number)</th>
<th data-quarto-table-cell-role="th">Fishing Exports (Millions)</th>
<th data-quarto-table-cell-role="th">Value</th>
<th data-quarto-table-cell-role="th">Country</th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Binned_Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>376896.50</td>
<td>485.10</td>
<td>12.00</td>
<td>5.0</td>
<td>1963.38</td>
<td>10.64</td>
<td>Australia</td>
<td>2000</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>55.25</td>
<td>5.65</td>
<td>0.33</td>
<td>0.0</td>
<td>739.13</td>
<td>0.00</td>
<td>Belgium</td>
<td>2000</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>24661.75</td>
<td>605.08</td>
<td>23.33</td>
<td>8.0</td>
<td>4431.00</td>
<td>5.23</td>
<td>Canada</td>
<td>2000</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>8849.75</td>
<td>2124.58</td>
<td>1.00</td>
<td>4.0</td>
<td>3118.12</td>
<td>19.05</td>
<td>Chile</td>
<td>2000</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>29421.75</td>
<td>235.18</td>
<td>0.00</td>
<td>0.0</td>
<td>321.71</td>
<td>0.00</td>
<td>Colombia</td>
<td>2000</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="class-distribution" class="level3">
<h3 class="anchored" data-anchor-id="class-distribution">Class Distribution</h3>
<p>This decision tree algorithm may be biased towards the majority class (bin 1), leading to lower accuracy for minority classes. You can see the class distribution results below.</p>
<div class="cell" data-execution_count="45">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>class_distribution <span class="op">=</span> trees[<span class="st">'Binned_Value'</span>].value_counts()</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Class Distribution:"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(class_distribution)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>class_distribution.plot(kind<span class="op">=</span><span class="st">'bar'</span>, rot<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'skyblue'</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Class Distribution'</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Binned_Value'</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Class Distribution:
Binned_Value
1    411
2     44
5     34
3     14
4     13
Name: count, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="classification_files/figure-html/cell-4-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="baseline-comparison" class="level3">
<h3 class="anchored" data-anchor-id="baseline-comparison">Baseline Comparison</h3>
<p>This baseline comparison can be used to act as a simple benchmark that helps us understand how well the decision tree models are performing and whether the chosen metrics are appropriate for your problem. If the decision tree model below cannot outperform this simple random prediction… there might be issues with the models or data.</p>
<div class="cell" data-execution_count="47">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> Counter</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, precision_recall_fscore_support</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Random Classifier function</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> random_classifier(y_data):</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    num_classes <span class="op">=</span> <span class="bu">len</span>(np.unique(y_data))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    ypred <span class="op">=</span> np.random.randint(<span class="dv">1</span>, num_classes <span class="op">+</span> <span class="dv">1</span>, size<span class="op">=</span><span class="bu">len</span>(y_data))  <span class="co"># Random predictions for Binned_Value classes</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"-----RANDOM CLASSIFIER-----"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Count of Predictions:"</span>, Counter(ypred).values())</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Probability of Predictions:"</span>, np.fromiter(Counter(ypred).values(), dtype<span class="op">=</span><span class="bu">float</span>) <span class="op">/</span> <span class="bu">len</span>(y_data))</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    accuracy <span class="op">=</span> accuracy_score(y_data, ypred)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    precision, recall, fscore, _ <span class="op">=</span> precision_recall_fscore_support(y_data, ypred, average<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Accuracy:"</span>, accuracy)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Precision (Class 1, Class 2, Class 3, Class 4, Class 5):"</span>, precision)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Recall (Class 1, Class 2, Class 3, Class 4, Class 5):"</span>, recall)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"F1-score (Class 1, Class 2, Class 3, Class 4, Class 5):"</span>, fscore)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> trees[<span class="st">'Binned_Value'</span>]</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>random_classifier(y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>-----RANDOM CLASSIFIER-----
Count of Predictions: dict_values([112, 100, 116, 97, 91])
Probability of Predictions: [0.21705426 0.19379845 0.2248062  0.1879845  0.17635659]
Accuracy: 0.17829457364341086
Precision (Class 1, Class 2, Class 3, Class 4, Class 5): [0.78021978 0.08247423 0.03       0.01724138 0.07142857]
Recall (Class 1, Class 2, Class 3, Class 4, Class 5): [0.17274939 0.18181818 0.21428571 0.15384615 0.23529412]
F1-score (Class 1, Class 2, Class 3, Class 4, Class 5): [0.28286853 0.11347518 0.05263158 0.03100775 0.10958904]</code></pre>
</div>
</div>
</section>
<section id="decision-tree-classifier" class="level3">
<h3 class="anchored" data-anchor-id="decision-tree-classifier">Decision Tree Classifier</h3>
<p>Using DecisionTreeClassifier from sklearn.tree we can implement a decision tree.</p>
<div class="cell" data-execution_count="35">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># X = ALL FEATURES BESIDES value, binned_value and country</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> trees.drop([<span class="st">'Value'</span>, <span class="st">'Binned_Value'</span>, <span class="st">'Country'</span>], axis <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Target variable is BINS (classifying data into these bins)</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> trees[<span class="st">'Binned_Value'</span>]</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Split dataset into training and testing </span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.3</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Decision Tree classifier</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> DecisionTreeClassifier(criterion<span class="op">=</span><span class="st">"entropy"</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Training Classifier</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> clf.fit(X_train, y_train)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicting response for dataset</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> clf.predict(X_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="evaluating-performance" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-performance">Evaluating Performance</h3>
<p>After implementing the decision tree, the accuracy score tells us that this model is 91% accurate. Furthermore, the precision, recall and f-1 scores are all very high as well.</p>
<div class="cell" data-execution_count="36">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy using accuracy score</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="op">=</span> accuracy_score(y_test, y_pred)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy:"</span>, accuracy)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Classification Report</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>classification_rep <span class="op">=</span> classification_report(y_test, y_pred)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Classification Report:</span><span class="ch">\n</span><span class="st">"</span>, classification_rep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy: 0.9161290322580645
Classification Report:
               precision    recall  f1-score   support

           1       0.96      0.95      0.96       128
           2       0.40      0.50      0.44         8
           3       0.67      0.67      0.67         3
           4       0.67      0.67      0.67         3
           5       1.00      0.92      0.96        13

    accuracy                           0.92       155
   macro avg       0.74      0.74      0.74       155
weighted avg       0.92      0.92      0.92       155
</code></pre>
</div>
</div>
<p><strong>Accuracy on the TRAINING vs TESTING set</strong></p>
<div class="cell" data-execution_count="22">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Code given in 5000 resources</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>test_results <span class="op">=</span> []</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>train_results <span class="op">=</span> []</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> num_layer <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">20</span>):</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> DecisionTreeClassifier(max_depth<span class="op">=</span>num_layer)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> model.fit(X_train, y_train)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    yp_train <span class="op">=</span> model.predict(X_train)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    yp_test <span class="op">=</span> model.predict(X_test)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    test_results.append([num_layer, accuracy_score(y_test, yp_test), recall_score(y_test, yp_test, average<span class="op">=</span><span class="st">'weighted'</span>)])</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    train_results.append([num_layer, accuracy_score(y_train, yp_train), recall_score(y_train, yp_train, average<span class="op">=</span><span class="st">'weighted'</span>)])</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>plt.plot([column[<span class="dv">1</span>] <span class="cf">for</span> column <span class="kw">in</span> train_results], marker<span class="op">=</span><span class="st">'o'</span>, color<span class="op">=</span><span class="st">"skyblue"</span>, label<span class="op">=</span><span class="st">"Training"</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>plt.plot([column[<span class="dv">1</span>] <span class="cf">for</span> column <span class="kw">in</span> test_results], marker<span class="op">=</span><span class="st">'o'</span>, color<span class="op">=</span><span class="st">"green"</span>, label<span class="op">=</span><span class="st">"Test"</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"ACCURACY: Training (blue) and Test (green)"</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Lyers in Decision Tree (max depth)"</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="classification_files/figure-html/cell-8-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="confusion-matrices" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrices">Confusion Matrices</h3>
<p>Confusion Matrices help evaluate the performance of a classification model by comparing its predictions to the actual ground truth.</p>
<div class="cell" data-execution_count="58">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> confusion_plot(y_actual, y_pred):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    accuracy <span class="op">=</span> accuracy_score(y_actual, y_pred)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    n_recall <span class="op">=</span> recall_score(y_actual, y_pred, average<span class="op">=</span><span class="va">None</span>, zero_division<span class="op">=</span><span class="dv">1</span>)[<span class="dv">0</span>]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    n_precision <span class="op">=</span> precision_score(y_actual, y_pred, average<span class="op">=</span><span class="va">None</span>, zero_division<span class="op">=</span><span class="dv">1</span>)[<span class="dv">0</span>]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    p_recall <span class="op">=</span> recall_score(y_actual, y_pred, average<span class="op">=</span><span class="va">None</span>, zero_division<span class="op">=</span><span class="dv">1</span>)[<span class="dv">1</span>]</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    p_precision <span class="op">=</span> precision_score(y_actual, y_pred, average<span class="op">=</span><span class="va">None</span>, zero_division<span class="op">=</span><span class="dv">1</span>)[<span class="dv">1</span>]</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    unique_labels <span class="op">=</span> np.unique(np.concatenate([y_actual, y_pred]))</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    cm <span class="op">=</span> confusion_matrix(y_actual, y_pred, labels<span class="op">=</span>unique_labels)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    disp <span class="op">=</span> ConfusionMatrixDisplay(confusion_matrix<span class="op">=</span>cm, display_labels<span class="op">=</span>unique_labels)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    disp.plot(cmap<span class="op">=</span><span class="st">'Blues'</span>, values_format<span class="op">=</span><span class="st">'d'</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">'Confusion Matrix'</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"ACCURACY:"</span>, accuracy)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"NEGATIVE RECALL (Y=0):"</span>, n_recall)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"NEGATIVE PRECISION (Y=0):"</span>, n_precision)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"POSITIVE RECALL (Y=1):"</span>, p_recall)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"POSITIVE PRECISION (Y=1):"</span>, p_precision)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(cm)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>confusion_plot(y_test, y_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="classification_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>ACCURACY: 0.8774193548387097
NEGATIVE RECALL (Y=0): 0.9609375
NEGATIVE PRECISION (Y=0): 0.9609375
POSITIVE RECALL (Y=1): 0.5
POSITIVE PRECISION (Y=1): 0.2222222222222222
[[123   5   0   0   0]
 [  4   4   0   0   0]
 [  1   2   0   0   0]
 [  0   1   0   2   0]
 [  0   6   0   0   7]]</code></pre>
</div>
</div>
<p>As you can see from this confusion matrix, the model did a good job predicting Bin 1 and Bin 2.</p>
</section>
<section id="plotting-tree" class="level3">
<h3 class="anchored" data-anchor-id="plotting-tree">Plotting Tree</h3>
<p>Below I have plotted the tree with a max depth of 3. I chose this max depth after looking at the training vs testing accuracy plot.</p>
<p>I also printed out the text for how this decision tree is working.</p>
<div class="cell" data-execution_count="50">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> DecisionTreeClassifier(criterion<span class="op">=</span><span class="st">"entropy"</span>, max_depth<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> clf.fit(X_train, y_train)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> clf.predict(X_test)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">10</span>))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>plot_tree(clf, feature_names<span class="op">=</span>X.columns.tolist(), class_names<span class="op">=</span>[<span class="bu">str</span>(label) <span class="cf">for</span> label <span class="kw">in</span> <span class="bu">sorted</span>(y.unique())], filled<span class="op">=</span><span class="va">True</span>, rounded<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="classification_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="52">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>tree_summary <span class="op">=</span> export_text(model, feature_names<span class="op">=</span>X_train.columns.tolist(), decimals<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tree_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>|--- Instruments (number) &lt;= 9.500
|   |--- Inventions (number) &lt;= 2.350
|   |   |--- Fishing Exports (Millions) &lt;= 1486.940
|   |   |   |--- Instruments (number) &lt;= 4.500
|   |   |   |   |--- Year &lt;= 2002.500
|   |   |   |   |   |--- Aqua Production (Millions) &lt;= 35545.000
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- Aqua Production (Millions) &gt;  35545.000
|   |   |   |   |   |   |--- Aqua Production (Millions) &lt;= 39355.750
|   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |--- Aqua Production (Millions) &gt;  39355.750
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- Year &gt;  2002.500
|   |   |   |   |   |--- class: 1
|   |   |   |--- Instruments (number) &gt;  4.500
|   |   |   |   |--- Aqua Production (Millions) &lt;= 4776.875
|   |   |   |   |   |--- class: 3
|   |   |   |   |--- Aqua Production (Millions) &gt;  4776.875
|   |   |   |   |   |--- class: 1
|   |   |--- Fishing Exports (Millions) &gt;  1486.940
|   |   |   |--- Aqua Production (Millions) &lt;= 3460.500
|   |   |   |   |--- Aqua Production (Millions) &lt;= 3290.375
|   |   |   |   |   |--- Marine Protected Area (sqkm) &lt;= 30.440
|   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |--- Marine Protected Area (sqkm) &gt;  30.440
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- Aqua Production (Millions) &gt;  3290.375
|   |   |   |   |   |--- class: 5
|   |   |   |--- Aqua Production (Millions) &gt;  3460.500
|   |   |   |   |--- Aqua Production (Millions) &lt;= 32825.375
|   |   |   |   |   |--- Year &lt;= 2007.500
|   |   |   |   |   |   |--- Year &lt;= 2002.500
|   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |--- Year &gt;  2002.500
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- Year &gt;  2007.500
|   |   |   |   |   |   |--- class: 2
|   |   |   |   |--- Aqua Production (Millions) &gt;  32825.375
|   |   |   |   |   |--- Marine Protected Area (sqkm) &lt;= 1455.430
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- Marine Protected Area (sqkm) &gt;  1455.430
|   |   |   |   |   |   |--- class: 4
|   |--- Inventions (number) &gt;  2.350
|   |   |--- Aqua Production (Millions) &lt;= 9.000
|   |   |   |--- class: 2
|   |   |--- Aqua Production (Millions) &gt;  9.000
|   |   |   |--- Aqua Production (Millions) &lt;= 1282211.000
|   |   |   |   |--- Marine Protected Area (sqkm) &lt;= 4557.840
|   |   |   |   |   |--- Marine Protected Area (sqkm) &lt;= 17.540
|   |   |   |   |   |   |--- Marine Protected Area (sqkm) &lt;= 8.865
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- Marine Protected Area (sqkm) &gt;  8.865
|   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |--- Marine Protected Area (sqkm) &gt;  17.540
|   |   |   |   |   |   |--- Year &lt;= 2002.500
|   |   |   |   |   |   |   |--- Inventions (number) &lt;= 41.165
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- Inventions (number) &gt;  41.165
|   |   |   |   |   |   |   |   |--- Fishing Exports (Millions) &lt;= 1688.025
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- Fishing Exports (Millions) &gt;  1688.025
|   |   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |--- Year &gt;  2002.500
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- Marine Protected Area (sqkm) &gt;  4557.840
|   |   |   |   |   |--- Inventions (number) &lt;= 14.750
|   |   |   |   |   |   |--- Aqua Production (Millions) &lt;= 82138.398
|   |   |   |   |   |   |   |--- class: 5
|   |   |   |   |   |   |--- Aqua Production (Millions) &gt;  82138.398
|   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |--- Inventions (number) &gt;  14.750
|   |   |   |   |   |   |--- class: 1
|   |   |   |--- Aqua Production (Millions) &gt;  1282211.000
|   |   |   |   |--- Fishing Exports (Millions) &lt;= 3567.535
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- Fishing Exports (Millions) &gt;  3567.535
|   |   |   |   |   |--- class: 2
|--- Instruments (number) &gt;  9.500
|   |--- Marine Protected Area (sqkm) &lt;= 1707.135
|   |   |--- Inventions (number) &lt;= 11.000
|   |   |   |--- Fishing Exports (Millions) &lt;= 429.785
|   |   |   |   |--- class: 2
|   |   |   |--- Fishing Exports (Millions) &gt;  429.785
|   |   |   |   |--- Marine Protected Area (sqkm) &lt;= 921.650
|   |   |   |   |   |--- class: 3
|   |   |   |   |--- Marine Protected Area (sqkm) &gt;  921.650
|   |   |   |   |   |--- Year &lt;= 2018.000
|   |   |   |   |   |   |--- class: 4
|   |   |   |   |   |--- Year &gt;  2018.000
|   |   |   |   |   |   |--- class: 3
|   |   |--- Inventions (number) &gt;  11.000
|   |   |   |--- class: 1
|   |--- Marine Protected Area (sqkm) &gt;  1707.135
|   |   |--- Fishing Exports (Millions) &lt;= 1902.460
|   |   |   |--- class: 4
|   |   |--- Fishing Exports (Millions) &gt;  1902.460
|   |   |   |--- class: 5
</code></pre>
</div>
</div>
<p>Explaining this DECISION TREE</p>
<p><strong>Root Node:</strong></p>
<ul>
<li>Instruments (number) &lt;= 9.500, is the starting point for the decision-making process. This condition splits the data into two branches based on whether this condition is true or false.</li>
</ul>
<p><strong>First Level:</strong></p>
<ul>
<li>If Instruments (number) &lt;= 9.500 is true, it further checks Inventions (number) &lt;= 2.350. If false, it follows the opposite branch.</li>
</ul>
<p><strong>Second Level:</strong></p>
<ul>
<li>If Instruments (number) &lt;= 9.500 and Inventions (number) &lt;= 2.350 are both true, it checks Fishing Exports (Millions) &lt;= 1486.940.</li>
</ul>
<p><strong>Third Level:</strong></p>
<ul>
<li>The tree continues to branch based on various conditions, etc</li>
</ul>
<p><strong>Leaf Nodes:</strong></p>
<ul>
<li>The leaf nodes provide the classification outcome based on the conditions met along the path from the root node to that leaf.</li>
</ul>
<p><strong>Class Labels:</strong></p>
<ul>
<li>Each leaf node has a class label (1, 2, 3, 4, 5) indicating the predicted class for the given set of conditions!!!!</li>
</ul>
</section>
</section>
<section id="random-forests" class="level2">
<h2 class="anchored" data-anchor-id="random-forests">Random Forests</h2>
<p>Additionally, I completed random forests on my data. Random forests are a collection of decision trees. Decision trees are the building blocks or random forests.</p>
<p>Random forests have three main hyperparameters, which need to be set before training. These include node size, the number of trees, and the number of features sampled. After setting these hyperparamters, the random forest classifier can be used to solve for regression or classification problems.</p>
<p>To learn more about random forests visit <a href="https://www.ibm.com/topics/random-forest">here</a></p>
<div class="cell" data-execution_count="53">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Specifying hyperparameters </span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>rf_classifier <span class="op">=</span> RandomForestClassifier(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    n_estimators<span class="op">=</span><span class="dv">100</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    criterion<span class="op">=</span><span class="st">"entropy"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    min_samples_split<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    min_samples_leaf<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    max_depth<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">1</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Train Random Forest Classifier</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>rf_classifier.fit(X_train, y_train)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>y_rf_pred <span class="op">=</span> rf_classifier.predict(X_test)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluation</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>rf_accuracy <span class="op">=</span> accuracy_score(y_test, y_rf_pred)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Random Forest Accuracy:"</span>, rf_accuracy)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>rf_classification_rep <span class="op">=</span> classification_report(y_test, y_rf_pred)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Random Forest Classification Report:</span><span class="ch">\n</span><span class="st">"</span>, rf_classification_rep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Accuracy: 0.967741935483871
Random Forest Classification Report:
               precision    recall  f1-score   support

           1       0.98      1.00      0.99       128
           2       0.83      0.62      0.71         8
           3       1.00      0.67      0.80         3
           4       1.00      0.67      0.80         3
           5       0.93      1.00      0.96        13

    accuracy                           0.97       155
   macro avg       0.95      0.79      0.85       155
weighted avg       0.97      0.97      0.96       155
</code></pre>
</div>
</div>
<section id="random-forest-confusion-matrix" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-confusion-matrix">Random Forest Confusion Matrix</h3>
<div class="cell" data-execution_count="54">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>rf_conf_matrix <span class="op">=</span> confusion_matrix(y_test, y_rf_pred)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>disp <span class="op">=</span> ConfusionMatrixDisplay(confusion_matrix<span class="op">=</span>rf_conf_matrix, display_labels<span class="op">=</span><span class="bu">sorted</span>(y.unique()))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>disp.plot(cmap<span class="op">=</span><span class="st">'Blues'</span>, values_format<span class="op">=</span><span class="st">'d'</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Confusion Matrix for Random Forest'</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="classification_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Once again, this model does a very good job predicting Bin 1. This is a result of bin 1 having the highest number of tuples within the dataset.</p>
</section>
</section>
<section id="results-and-conclusions" class="level2">
<h2 class="anchored" data-anchor-id="results-and-conclusions">Results and Conclusions</h2>
<p>Overall the decision tree and random forest models have very high accuracy. Although, this may be due to the large number of countries that fall within Bin 1 - as shown by the class distribution.</p>
<p>Decision trees are a very intuitive machine learning model. This model allows readers to see what attributes are taken into account when classifying a tuple as sustainable.</p>
<p>A few interesting things to point out:</p>
<ul>
<li>The top most condition is based off of Policy Instruments. Policy Instruments are the amount of policy that has been released per year relating to sustainability (not just ocean sustainabiloty) by country.</li>
<li>The random forest algorithm preformed better than the classification decision tree!</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>